drop table if exists plan;
create table plan
(
    plan_id serial primary key,     /* 計画id */
    plan_year int not null,         /* 年 */
    plan_month int not null,        /* 月 */
    seiban text not null,           /* 製番 */
    location_id int,                /* ロケーションid */
    item_id int not null,           /* 品目id */
    classification int not null,    /* 区分「0(計画)/1(受注)/2(予約)/3(計算)」 */
    plan_quantity numeric not null, /* 数量 */

    day1 numeric not null,
    day2 numeric not null,
    day3 numeric not null,
    day4 numeric not null,
    day5 numeric not null,
    day6 numeric not null,
    day7 numeric not null,
    day8 numeric not null,
    day9 numeric not null,
    day10 numeric not null,
    day11 numeric not null,
    day12 numeric not null,
    day13 numeric not null,
    day14 numeric not null,
    day15 numeric not null,
    day16 numeric not null,
    day17 numeric not null,
    day18 numeric not null,
    day19 numeric not null,
    day20 numeric not null,
    day21 numeric not null,
    day22 numeric not null,
    day23 numeric not null,
    day24 numeric not null,
    day25 numeric not null,
    day26 numeric not null,
    day27 numeric not null,
    day28 numeric not null,
    day29 numeric not null,
    day30 numeric not null,
    day31 numeric not null,
    remarks text not null,

    /* オーダー済み数 */
    order1 numeric,
    order2 numeric,
    order3 numeric,
    order4 numeric,
    order5 numeric,
    order6 numeric,
    order7 numeric,
    order8 numeric,
    order9 numeric,
    order10 numeric,
    order11 numeric,
    order12 numeric,
    order13 numeric,
    order14 numeric,
    order15 numeric,
    order16 numeric,
    order17 numeric,
    order18 numeric,
    order19 numeric,
    order20 numeric,
    order21 numeric,
    order22 numeric,
    order23 numeric,
    order24 numeric,
    order25 numeric,
    order26 numeric,
    order27 numeric,
    order28 numeric,
    order29 numeric,
    order30 numeric,
    order31 numeric,

    custom_text_1 text,	/* (15i) カスタム項目 */
    custom_text_2 text,
    custom_text_3 text,
    custom_text_4 text,
    custom_text_5 text,
    custom_text_6 text,
    custom_text_7 text,
    custom_text_8 text,
    custom_text_9 text,
    custom_text_10 text,
    custom_date_1 date,
    custom_date_2 date,
    custom_date_3 date,
    custom_date_4 date,
    custom_date_5 date,
    custom_date_6 date,
    custom_date_7 date,
    custom_date_8 date,
    custom_date_9 date,
    custom_date_10 date,
    custom_numeric_1 numeric,
    custom_numeric_2 numeric,
    custom_numeric_3 numeric,
    custom_numeric_4 numeric,
    custom_numeric_5 numeric,
    custom_numeric_6 numeric,
    custom_numeric_7 numeric,
    custom_numeric_8 numeric,
    custom_numeric_9 numeric,
    custom_numeric_10 numeric,

    record_creator text,
    record_create_date timestamp,
    record_create_func text,
    record_updater text,
    record_update_date timestamp,
    record_update_func text
);
create unique index plan_unique_index0 on plan(plan_year, plan_month, item_id, classification);